//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBotDBAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatBotDBEntities2 : DbContext
    {
        public ChatBotDBEntities2()
            : base("name=ChatBotDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
    }
}
