//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatBotDBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public int Id { get; set; }
        public string SeriesName { get; set; }
        public string Category { get; set; }
        public string ModelNo { get; set; }
        public string Spec1 { get; set; }
        public string Spec2 { get; set; }
        public string Spec3 { get; set; }
        public string url { get; set; }
    }
}
